[workspace]
members = [
    'app',
    'config',
    'dao',
    'service',
    'twitch',
    'types',
    'utils',
    'web_server'
]

[workspace.dependencies]
# System
anyhow = "1.0"
# Serde
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# Validation
validator = { version = "0.16", features = ["derive"] }
# Data Types
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.4", features = ["v4", "fast-rng", "serde"] }
# Web
axum = { version = "0.6", features = ["tokio", "json", "headers"] }