[package]
name = "yggdrasil"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# System
dotenvy = "0.15"
anyhow = "1.0"
uuid = { version = "1.4", features = ["v4", "fast-rng", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["json"] }
jsonwebtoken = "8"
# Serialize
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# Web Server
tokio = { version = "1.32", features = ["full"] }
axum = { version = "0.6", features = ["tokio", "json", "headers"] }
# Logging
tower-http = { version = "0.4", features = ["trace", "cors", "timeout"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json"] }
# Database
sqlx = { version = "0.7", features = [
  "runtime-tokio",
  "postgres",
  "migrate",
  "uuid",
  "json",
  "chrono",
] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
