services:
  app:
    image: ghcr.io/wibruhtor/yggdrasil:main
    container_name: yggdrasil
    restart: on-failure
    depends_on:
      pg:
        condition: service_healthy
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - wibruhtor_network
  pg:
    image: postgres:15
    container_name: wibruhtor-postgres
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - wibruhtor_network

networks:
  wibruhtor_network:
