services:
  pg:
    image: postgres:15
    container_name: wibruhtor-postgres-dev
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: wibruhtor
      POSTGRES_PASSWORD: secret-password
    networks:
      - wibruhtor_network

networks:
  wibruhtor_network:
