FROM rust:1.72

WORKDIR /app

EXPOSE 3000

COPY ./Cargo.toml ./Cargo.toml
COPY ./Cargo.lock ./Cargo.lock
COPY ./migrations ./migrations
COPY ./src ./src
COPY ./.sqlx ./.sqlx

RUN cargo install cargo-watch

CMD ["cargo", "run"]
