receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

extensions:
  basicauth/otlp:
    client_auth:
      username: 755035
      password: glc_eyJvIjoiOTU4MDM5IiwibiI6ImFsbC1vdGVsIiwiayI6IlpXUzc4ODdoWTlPU21HQjMyWTNVNHJpNSIsIm0iOnsiciI6InVzIn19

exporters:
  otlphttp:
    auth:
      authenticator: basicauth/otlp
    endpoint: https://otlp-gateway-prod-us-east-0.grafana.net/otlp

service:
  extensions: [ basicauth/otlp ]
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlphttp ]
