receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

extensions:
  basicauth/otlp:
    client_auth:
      username: <instance_id>
      password: <token>

exporters:
  otlphttp:
    auth:
      authenticator: basicauth/otlp
    endpoint: https://otlp-gateway-<zone>.grafana.net/otlp

service:
  extensions: [ basicauth/otlp ]
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ otlphttp ]
