[package]
name = "app"
version = "1.0.0"
edition = "2021"

[dependencies]
# Internal
config = { workspace = true }
dao = { workspace = true }
types = { workspace = true }
# Utilities
tokio = { workspace = true }
