[package]
name = "config"
version = "1.0.0"
edition = "2021"

[dependencies]
# Internal
types = { workspace = true }
# Observability
tracing = { workspace = true }
# Utilities
dotenvy = { workspace = true }

[dev-dependencies]
# Testing
fake = { workspace = true }
