[package]
name = "config"
version = "1.0.0"
edition = "2021"

[dependencies]
# System
dotenvy = { workspace = true }
# Data Types
types = { path = "../types" }
# Observability
tracing = { workspace = true }