[package]
name = "utils"
version = "1.0.0"
edition = "2021"

[dependencies]
# System
anyhow = "1.0"
# Serde
serde = { workspace = true }
# Validation
validator = { version = "0.16", features = ["derive"] }
# Data Types
chrono = { workspace = true }
uuid = { workspace = true }
types = { path = "../types" }
jsonwebtoken = "8"
# Web
axum = { workspace = true }
# Crypt
magic-crypt = "3.1"