[package]
name = "utils"
version = "1.0.0"
edition = "2021"

[dependencies]
magic-crypt = "3.1"
axum = { version = "0.6", default-features = false }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.4", features = ["v4", "fast-rng", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "8"
types = { path = "../types" }